home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('story-1/', views.index, name='index'),
]

ppwaran/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story-1/', include('home.urls', namespace="story-1")),
    path('', include('storyprofile.urls', namespace="storyprofile")),
    path('story-5/', include('story5.urls', namespace="story5")),
    path('story-6/', include('story6.urls', namespace="story6"))
]

story5/urls.py
from django.urls import path, include

from . import views

app_name = 'story5'

urlpatterns = [
    path('matkul/', views.matkul, name='matkul'),
    path('isi/', views.isi, name='isi'),
    path('daftar/', views.daftar, name='daftar'),
    path('delete/P<int:id_delete>/', views.delete, name='delete'),
    path('detail/P<int:id_matkul>/', views.detail, name='detail'),
]

story6/urls.py
from django.urls import path, include

from . import views

app_name = 'story6'

urlpatterns = [
    path('index-aktivitas/', views.indexAktivitas, name='indexAktivitas'),
    path('daftar-aktivitas/', views.daftarAktivitas, name='daftarAktivitas'),
    path('list-aktivitas/', views.listAktivitas, name='listAktivitas'),
    path('delete/P<int:id_delete>/', views.deleteOrang, name='deleteOrang'),
    path('daftar-orang/P<int:id_daftar>/', views.daftarOrang, name='daftarOrang'),
]

storyprofile/urls.py
from django.urls import path

from . import views

app_name = 'storyprofile'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('gallery/', views.gallery, name='gallery')
]

home/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

# Create your models here.

class MatkulModel(models.Model):
    mata_kuliah = models.CharField(max_length=100)
    dosen = models.CharField(max_length=100)
    sks = models.CharField(max_length=1)
    deskripsi = models.TextField(null=True)
    semester = models.CharField(max_length=60)
    ruang = models.CharField(max_length=60)

story6/models.py
from django.db import models

# Create your models here.
class ModelAktivitas(models.Model):
    nama_aktivitas = models.CharField(max_length=100)
    deskripsi_aktivitas = models.TextField(null=True)

    def __str__ (self):
        return self.nama_aktivitas

class ModelOrang(models.Model):
    nama_orang = models.CharField(max_length=100)
    aktivitas = models.ForeignKey(ModelAktivitas, on_delete=models.CASCADE, null=True, blank=True)

    def __str__ (self):
        return self.nama_orang  

storyprofile/models.py
from django.db import models

# Create your models here.

story5/forms.py
from django import forms

class FormMatkul(forms.Form):
    mata_kuliah = forms.CharField(max_length=100)
    dosen = forms.CharField(max_length=100)
    sks = forms.CharField(max_length=1)
    deskripsi = forms.CharField(
        widget = forms.Textarea
    )
    semester = forms.CharField(max_length=60)
    ruang = forms.CharField(max_length=60)

story6/forms.py
from django import forms

class FormOrang(forms.Form):
    nama_orang = forms.CharField(max_length=100)

class FormAktivitas(forms.Form):
    nama_aktivitas = forms.CharField(max_length=100)
    deskripsi_aktivitas = forms.CharField(
        widget = forms.Textarea
    )

home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'home/index.html')

story5/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect

# Create your views here.
from .forms import FormMatkul
from .models import MatkulModel

def matkul(request):
    return render(request, 'story5/matkul.html')

def isi(request):
    form_matkul = FormMatkul(request.POST or None)

    if request.method == 'POST':
        if form_matkul.is_valid():
            MatkulModel.objects.create(
                mata_kuliah = form_matkul.cleaned_data.get('mata_kuliah'),
                dosen = form_matkul.cleaned_data.get('dosen'),
                sks = form_matkul.cleaned_data.get('sks'),
                deskripsi = form_matkul.cleaned_data.get('deskripsi'),
                semester = form_matkul.cleaned_data.get('semester'),
                ruang = form_matkul.cleaned_data.get('ruang'),
            )
            return HttpResponseRedirect("/story-5/daftar/")

    context = {
        'title':'Daftarkan Jadwal',
        'form_matkul':form_matkul
    }
    return render(request,'story5/isi.html', context)

def daftar(request):
    matkuls = MatkulModel.objects.all()
    context = {
        'title':'Daftar Mata Kuliah',
        'matkuls':matkuls,
    }
    return render(request, 'story5/daftar.html', context)

def detail(request, id_matkul):
    matkul = MatkulModel.objects.filter(id=id_matkul).get(id=id_matkul)
    response = {
        'matkul':matkul,
    }
    return render(request, 'story5/detailmatkul.html', response)

def delete(request, id_delete):
    try:
        delete_jadwal = MatkulModel.objects.filter(id=id_delete)
        delete_jadwal.delete()
        return redirect('story5:daftar')
    except:
        return redirect('story5:daftar')

story6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect

# Create your views here.
from .forms import FormOrang, FormAktivitas
from .models import ModelOrang, ModelAktivitas

def indexAktivitas(request):
    return render(request, 'story6/indexaktivitas.html')

def daftarAktivitas(request):
    form_aktivitas = FormAktivitas()
    if request.method == 'POST':
        input_form_aktivitas = FormAktivitas(request.POST)
        if input_form_aktivitas.is_valid():
            ModelAktivitas.objects.create(
                nama_aktivitas = input_form_aktivitas.cleaned_data.get('nama_aktivitas'),
                deskripsi_aktivitas = input_form_aktivitas.cleaned_data.get('deskripsi_aktivitas'),
            )
            return HttpResponseRedirect("/story-6/list-aktivitas/")
    context = {
        'form_aktivitas':form_aktivitas
    }
    return render(request,'story6/daftaraktivitas.html', context)

def listAktivitas(request):
    aktivitass = ModelAktivitas.objects.all()
    orangs = ModelOrang.objects.all()
    context = {
        'aktivitass':aktivitass,
        'orangs':orangs,
    }
    return render(request, 'story6/listaktivitas.html', context)

def deleteOrang(request, id_delete):
    try:
        delete_orang = ModelOrang.objects.filter(id=id_delete)
        delete_orang.delete()
        return redirect('story6:listAktivitas')
    except:
        return redirect('story6:listAktivitas')

def daftarOrang(request, id_daftar):
    form_orang = FormOrang()
    if request.method == 'POST':
        input_form_orang = FormOrang(request.POST)
        if input_form_orang.is_valid():
            data = input_form_orang.cleaned_data
            objek_orang = ModelOrang()
            objek_orang.nama_orang = data['nama_orang']
            objek_orang.aktivitas = ModelAktivitas.objects.get(id=id_daftar)
            objek_orang.save()
            return HttpResponseRedirect("/story-6/list-aktivitas/")
    context = {
        'form_orang':form_orang
    }
    return render(request,'story6/daftarorang.html', context)

storyprofile/views.py
from django.shortcuts import render

# Create your views here.
def profile(request):
    return render(request, 'storyprofile/profile.html')

def gallery(request):
    return render(request, 'storyprofile/gallery.html')

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Aran's Profile</title>
</head>
<body>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Montserrat:wght@500&display=swap" rel="stylesheet">
    <h1 style="font-family: 'Bebas Neue', cursive;text-align: center;">Hello!</h1>
    <img src="{% static 'profpict.jpg' %}" alt="profile picture" style="width:250px; height:250px; display: block; margin-left: auto; margin-right: auto">
    <h2 style="font-family: 'Bebas Neue', cursive; text-align: center; font-size: 40px;"><span style="color:darkcyan;">Aran</span>sandya Pangesthika Arrumy</h2>
    <p style="font-family: 'Montserrat', sans-serif; text-align: center;">Information Systems Student at Fakultas Ilmu Komputer Universitas Indonesia</p>
    <p style="font-family: 'Montserrat', sans-serif; text-align: center;">Student Number: 1906353750 | Class of 2019 | Hobby: Listening to music</p>
    <br>
    <h3 style="font-family: 'Bebas Neue', cursive; text-align: center;font-size: 30px;">Get to know me better!</h3>
    <p style="font-family: 'Montserrat', sans-serif; padding-right: 400px; padding-left: 400px;">Hello, there! My name is Aransandya Pangesthika Arrumy. You can call me <span style="color: darkcyan;"><b>Aran</b></span>.
        I am an 18-years-old-student majoring in Information Systems at Fasilkom UI.
        I was born in Jakarta on October 5th. My hobby is listening to music.
        I love listening to a Korean Band called DAY6.
        I also love making new friends as I like to interact with people!
    </p>
    <br>
    <button style="border: none; display: block; margin-left: auto; margin-right: auto; color: black; background-color: darkcyan; font-size: 18px; text-align: center; font-family: 'Bebas Neue', cursive; padding: 15px 32px;"><a href="{% url 'storyprofile:profile' %}#">click here to go to another website page of mine</a></button>
    <h3 style="font-family: 'Bebas Neue', cursive; text-align: center;font-size: 30px;">Education</h3>
    <table style= "margin-left:auto; margin-right: auto;">
        <tr>
            <th style="border-bottom: 1px solid #ddd; font-family: 'Montserrat', sans-serif; width:200px">Year</th>
            <th style="border-bottom: 1px solid #ddd; font-family: 'Montserrat', sans-serif; width:200px">Stage</th>
            <th style="border-bottom: 1px solid #ddd; font-family: 'Montserrat', sans-serif; width:200px">Institution</th>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #ddd; font-family: 'Montserrat', sans-serif; text-align: center;">2004 - 2007</td>
            <td style="border-bottom: 1px solid #ddd; font-family: 'Montserrat', sans-serif; text-align: center;">Kindergarten</td>
            <td style="border-bottom: 1px solid #ddd; font-family: 'Montserrat', sans-serif; text-align: center;">TK Islam Al-Ikhsan</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #ddd; font-family: 'Montserrat', sans-serif; text-align: center;">2007 - 2013</td>
            <td style="border-bottom: 1px solid #ddd; font-family: 'Montserrat', sans-serif; text-align: center;">Elementary School</td>
            <td style="border-bottom: 1px solid #ddd; font-family: 'Montserrat', sans-serif; text-align: center;">SD Negeri Cipinang Melayu 03 Pagi</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #ddd; font-family: 'Montserrat', sans-serif; text-align: center;">2013 - 2016</td>
            <td style="border-bottom: 1px solid #ddd; font-family: 'Montserrat', sans-serif; text-align: center;">Junior High School</td>
            <td style="border-bottom: 1px solid #ddd; font-family: 'Montserrat', sans-serif; text-align: center;">SMP Negeri 115 Jakarta</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #ddd; font-family: 'Montserrat', sans-serif; text-align: center;">2016 - 2019</td>
            <td style="border-bottom: 1px solid #ddd; font-family: 'Montserrat', sans-serif; text-align: center;">Senior High School</td>
            <td style="border-bottom: 1px solid #ddd; font-family: 'Montserrat', sans-serif; text-align: center;">SMA Negeri 81 Jakarta</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #ddd; font-family: 'Montserrat', sans-serif; text-align: center;">2019 - Present</td>
            <td style="border-bottom: 1px solid #ddd; font-family: 'Montserrat', sans-serif; text-align: center;">College</td>
            <td style="border-bottom: 1px solid #ddd; font-family: 'Montserrat', sans-serif; text-align: center;">Universitas Indonesia</td>
        </tr>
    </table>
    <br>
    <h3 style="font-family: 'Bebas Neue', cursive; text-align: center;font-size: 30px;">Let's Get Connected!</h3>
    <center>
        <a href="https://www.instagram.com/aransandya"><img src="{% static 'ig.png' %}" style="margin-left: auto; margin-right: auto; width:60px; height:60px"></a>
        <a href="https://www.linkedin.com/in/aransandya-pangesthika-arrumy-5317051a2/?originalSubdomain=id"><img src="{% static 'linkedin.png' %}" style="margin-left: auto; margin-right: auto; width:60px; height:60px"></a>
    </center>
</body>
</html>

story5/templates/story5/daftar.html
{% extends 'base.html' %}

{% block main %}
<style>
    .text-th{
        font-family: 'DM Serif Display', serif;
    }
    .text-td{
        font-family: 'Poppins', sans-serif;
    }
</style>

<div style="margin-top: 80px;">
    <table class="table">
        <thead>
        <tr>
            <th scope="col" class="text-th">Mata Kuliah</th>
            <th scope="col" class="text-th">Dosen</th>
            <th scope="col" class="text-th">SKS</th>
            <th scope="col" class="text-th">Deskripsi</th>
            <th scope="col" class="text-th">Semester</th>
            <th scope="col" class="text-th">Ruang</th>
            <th scope="col" class="text-th">Delete?</th>
        </tr>
        </thead>
        <tbody>
            {% for matkul in matkuls %}
                <tr>
                    <td class="text-td"><a href="{% url 'story5:detail' matkul.id %}">{{matkul.mata_kuliah}}</a></td>
                    <td class="text-td">{{matkul.dosen}}</td>
                    <td class="text-td">{{matkul.sks}}</td>
                    <td class="text-td">{{matkul.deskripsi}}</td>
                    <td class="text-td">{{matkul.semester}}</td>
                    <td class="text-td">{{matkul.ruang}}</td>
                    <td>
                        <a href="{% url 'story5:delete' matkul.id %}" class="btn btn-danger" style="font-family: 'DM Serif Display', serif;">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="row mb-3 justify-content-center">
    <div class="col text-center">
        <a href="{% url 'story5:isi' %}" class="btn btn-dark" style="font-family: 'DM Serif Display', serif;">Tambah Jadwal</a>
    </div>
</div>
{% endblock main %}

story5/templates/story5/detailmatkul.html
{% extends 'base.html' %}
{% block main %}
<style>
    .text-th{
        font-family: 'DM Serif Display', serif;
    }
    .text-td{
        font-family: 'Poppins', sans-serif;
    }
</style>
<div class="col text-center" style="margin-top: 200px;">
    <table style="width: 100%; text-align: justify;">
        <tr>
            <th class="text-th">Mata Kuliah:</th>
            <td class="text-td">{{matkul.mata_kuliah}}</td>
        </tr>
        <tr>
            <th class="text-th">Dosen:</th>
            <td class="text-td">{{matkul.dosen}}</td>
        </tr>
        <tr>
            <th class="text-th">SKS:</th>
            <td class="text-td">{{matkul.sks}}</td>
        </tr>
        <tr>
            <th class="text-th">Deskripsi:</th>
            <td class="text-td">{{matkul.deskripsi}}</td>
        </tr>
        <tr>
            <th class="text-th">Semester:</th>
            <td class="text-td">{{matkul.ruang}}</td>
        </tr>
        <tr>
            <th class="text-th">Ruang:</th>
            <td class="text-td">{{matkul.ruang}}</td>
        </tr>
    </table>
</div>
<br>
<div class="row mb-3 justify-content-center">
    <div class="col text-center">
        <a href="{% url 'story5:daftar' %}" class="btn btn-dark" style="font-family: 'DM Serif Display', serif;">Kembali</a>
    </div>
</div>

{% endblock main %}

story5/templates/story5/isi.html
{% extends 'base.html' %} {% load static %}

{% block main %}
<div style="margin-top: 10vh;">
    <h1 style="font-family: 'DM Serif Display', serif;">{{title}}</h1>
</div>
<div>
    <form method="POST">
        {% csrf_token %}
        <table style="text-align: justify; font-family: 'Poppins', sans-serif;">
            {{form_matkul.as_table}}
        </table>
        <br>
        <button type="submit" class="btn btn-dark" style="font-family: 'DM Serif Display', serif;">Save</button>
    </form>
</div>

{% endblock main %}

story5/templates/story5/matkul.html
{% extends 'base.html' %} {% load static %}


{% block main %}
<div class="jumbotron">
    <h1 class="display-4" style="font-family: 'DM Serif Display', serif;">Schedule</h1>
    <p class="lead" style="font-family: 'Poppins', sans-serif;">Hello! This is where you can make a list of your schedules
    </p>
    <hr class="my-4">
    <p style="font-family: 'Poppins', sans-serif;">Choose "Create Schedule" to make new schedule and choose "See Schedule" to see list of schedules</p>
    <a class="btn btn-dark btn-lg" href="{% url 'story5:isi' %}" role="button" style="font-family: 'DM Serif Display', serif;">Create Schedule</a>
    <a class="btn btn-dark btn-lg" href="{% url 'story5:daftar' %}" role="button" style="font-family: 'DM Serif Display', serif;">See Schedule</a>
</div>
{% endblock main %}

story6/templates/story6/daftaraktivitas.html
{% extends 'base.html' %} {% load static %}

{% block main %}

<div style="margin-top: 10vh;">
    <h1 style="font-family: 'DM Serif Display', serif;">Daftarkan aktivitasmu di sini</h1>
</div>
<div>
    <form method="POST">
        {% csrf_token %}
        <table style="text-align: justify; font-family: 'Poppins', sans-serif;">
            {{form_aktivitas.as_table}}
        </table>
        <br>
        <button type="submit" class="btn btn-dark" style="font-family: 'DM Serif Display', serif;">Save</button>
    </form>
</div>

{% endblock main %}

story6/templates/story6/daftarorang.html
{% extends 'base.html' %} {% load static %}

{% block main %}

<div style="margin-top: 10vh;">
    <h1 style="font-family: 'DM Serif Display', serif;">Daftarkan namamu di kegiatan ini</h1>
</div>
<div>
    <form method="POST">
        {% csrf_token %}
        <table style="text-align: justify; font-family: 'Poppins', sans-serif;">
            {{form_orang.as_table}}
        </table>
        <br>
        <button type="submit" class="btn btn-dark" style="font-family: 'DM Serif Display', serif;">Save</button>
    </form>
</div>

{% endblock main %}

story6/templates/story6/indexaktivitas.html
{% extends 'base.html' %} {% load static %}


{% block main %}
<div class="jumbotron">
    <h1 class="display-4" style="font-family: 'DM Serif Display', serif;">Activities</h1>
    <p class="lead" style="font-family: 'Poppins', sans-serif;">Hello! This is where you can set your activities and register yourself to join the activity you're insterested in
    </p>
    <hr class="my-4">
    <p style="font-family: 'Poppins', sans-serif;">Choose "Create New Activity" to make new activity and choose "See Activities" to see list of activities and to register yourself</p>
    <a class="btn btn-dark btn-lg" href="{% url 'story6:daftarAktivitas' %}" role="button" style="font-family: 'DM Serif Display', serif;">Create New Activity</a>
    <a class="btn btn-dark btn-lg" href="{% url 'story6:listAktivitas' %}" role="button" style="font-family: 'DM Serif Display', serif;">See Activities</a>
</div>
{% endblock main %}

story6/templates/story6/listaktivitas.html
{% extends 'base.html' %} {% load static %}

{% block main %}
<div style="margin-top: 10vh;">
    <h1 style="font-family: 'DM Serif Display', serif; text-align: center;">Daftar Aktivitas</h1>
</div>

<div class="row w-100 justify-content-center">
    {% for aktivitas in aktivitass %}
    <div class="col-4 m-4 p-4 rounded border">
        <ul class="list-group">
        <li class="list-group-item list-group-item-dark" style="font-family: 'DM Serif Display', serif;">{{aktivitas.nama_aktivitas}}</li>
        {% for orang in orangs %}
        {% if orang.aktivitas == aktivitas %}
        <li class="list-group-item">
            <div style="font-family: 'Poppins', sans-serif;" class="">
                {{orang.nama_orang}}
                <a href="{% url 'story6:deleteOrang' orang.id %}" class="btn btn-danger float-right" style="font-family: 'DM Serif Display', serif;">Delete</a>
            </div>
        </li>
        {% endif %}
        {% endfor %}
        </ul>
        <div class="row mb-3 justify-content-center mt-5">
            <a href="{% url 'story6:daftarOrang' aktivitas.id %}" class="btn btn-dark" style="font-family: 'DM Serif Display', serif;">Register</a>
        </div>
    </div>
    {% endfor %}
</div>
<div class="row mb-3 justify-content-center">
    <div class="col text-center">
        <a href="{% url 'story6:indexAktivitas' %}" class="btn btn-dark" style="font-family: 'DM Serif Display', serif;">Kembali</a>
    </div>
</div>

{% endblock main %}

storyprofile/templates/storyprofile/gallery.html
{% extends 'base.html' %} {% load static %}
{% block main %}
<br>
<br>
<br>
<div class="gallery">
    <p class="p1-gal">my gallery</p>
    <p class="p2-gal">documentations of aran's everyday life</p>
</div>
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
    <div class="carousel-item active">
        <img src="{% static 'car1.jpg' %}" class="d-block w-100" alt="pict">
        <div class="carousel-caption d-none d-md-block">
        <h5 style="font-family: 'DM Serif Display', serif; color: black;">gallery</h5>
        <p style="font-family: 'DM Serif Display', serif; color: black;">documentations of aran's everyday life.</p>
        </div>
        </div>
        <div class="carousel-item">
        <img src="{% static 'car2.jpg' %}" class="d-block w-100" alt="pict">
        <div class="carousel-caption d-none d-md-block">
            <h5 style="font-family: 'DM Serif Display', serif; color: black;">gallery</h5>
            <p style="font-family: 'DM Serif Display', serif; color: black;">documentations of aran's everyday life.</p>
        </div>
        </div>
        <div class="carousel-item">
        <img src="{% static 'car3.jpg' %}" class="d-block w-100" alt="pict">
        <div class="carousel-caption d-none d-md-block">
            <h5 style="font-family: 'DM Serif Display', serif; color: black;">gallery</h5>
            <p style="font-family: 'DM Serif Display', serif; color: black;">documentations of aran's everyday life.</p>
        </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<br>
<br>
<div class="text-center pict-1">
    <figure class="figure">
        <img src="{% static 'psdm.jpg' %}" class="figure-img img-fluid rounded" alt="psdm" style="width: 700px; height: 500px;">
        <figcaption class="figure-caption capt-gal">Human Research Development Bureau of BEM Fasilkom UI 2020.</figcaption>
    </figure>
</div>
<br>
<div class="text-center pict-1">
    <figure class="figure">
        <img src="{% static 'finance.jpg' %}" class="figure-img img-fluid rounded" alt="finance" style="width: 700px; height: 500px;">
        <figcaption class="figure-caption capt-gal">Finance Team of COMPFEST12.</figcaption>
    </figure>
</div>
<br>
<div class="text-center pict-1">
    <figure class="figure">
        <img src="{% static 'wisgan.jpg' %}" class="figure-img img-fluid rounded" alt="wisgan" style="width: 700px; height: 500px;">
        <figcaption class="figure-caption capt-gal">Me with my friends as committees at Wisuda Ganjil 2020.</figcaption>
    </figure>
</div>
{% endblock main %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>✰ | Aransandya</title>
        <link rel="icon" href="{% static 'logo.png' %}" type="image/icon type">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link href="{% static 'style.css' %}" rel="stylesheet" type="text/css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <a class="navbar-brand" href="{% url 'storyprofile:profile' %}#"><img src="{% static 'logo.png' %}" alt="logo" style="width: 40px;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
                <a class="nav-item nav-link" href="{% url 'storyprofile:profile' %}#about" style="font-family: 'Poppins', sans-serif">about</a>
                <a class="nav-item nav-link" href="{% url 'storyprofile:profile' %}#skill" style="font-family: 'Poppins', sans-serif">skill</a>
                <a class="nav-item nav-link" href="{% url 'storyprofile:profile' %}#edu" style="font-family: 'Poppins', sans-serif">education</a>
                <a class="nav-item nav-link" href="{% url 'storyprofile:profile' %}#experience " style="font-family: 'Poppins', sans-serif">experience</a>
                <a class="nav-item nav-link" href="{% url 'storyprofile:profile' %}#contact" style="font-family: 'Poppins', sans-serif">contact</a>
                <a class="nav-item nav-link" href="{% url 'storyprofile:gallery' %}" style="font-family: 'Poppins', sans-serif">gallery</a>
                <a class="nav-item nav-link" href="{% url 'story-1:index' %}" style="font-family: 'Poppins', sans-serif">story 1</a>
                <a class="nav-item nav-link" href="{% url 'story5:matkul' %}" style="font-family: 'Poppins', sans-serif">schedule</a>
                <a class="nav-item nav-link" href="{% url 'story6:indexAktivitas' %}" style="font-family: 'Poppins', sans-serif">activities</a>
            </div>
            </div>
        </nav>
        {% block main %} {% endblock main %}
    </body>
</html>